Update CLI to be more Unix friendly
mike-lischke/antlr-format pull request #12
Opened 2024-06-28 14:51 UTC by jimidle

- Ensures files always end with a newline, which is required for UNIX text files.
- Does not overwrite the incoming file if it has not changed it, which is standard UNIX
  practice for files processed in-place.

2024-06-28 17:56 UTC, mike-lischke requested changes

2024-06-28 17:56 UTC, mike-lischke commented on cli/antlr-format.ts
>   * @returns The formatted grammar and the computed start and stop indices.
Would you mind updating the description as well? The result has changed, so..

2024-06-29 03:14 UTC, jimidle commented
Sure. Didn’t spot that.

On Fri, Jun 28, 2024 at 11:57 Mike Lischke ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In cli/antlr-format.ts
> <https://github.com/mike-lischke/antlr-format/pull/12#discussion_r1659124718>
> :
>
> > @@ -109,7 +108,7 @@ const defaultOptions: IFormattingOptions = {
>   * @returns The formatted grammar and the computed start and stop indices.
>
> Would you mind updating the description as well? The result has changed,
> so..
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mike-lischke/antlr-format/pull/12#pullrequestreview-2148647383>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJ7TMG222WGQGG5HBLYQ6LZJWPXFAVCNFSM6AAAAABKCBS6OCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNBYGY2DOMZYGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-22 07:05 UTC, mike-lischke commented
hey Jim, please update the description if you want this PR to be merged.

2024-11-08 20:47 UTC, closed without merging